#!/usr/bin/env bash
alias bm2='./bin/magento'
alias bm2cc='./bin/magento cache:clean'
alias bm2cf='./bin/magento cache:flush'
alias bm2su='./bin/magento setup:upgrade'
alias bm2sdc='./bin/magento setup:di:compile'
alias bm2ssd='./bin/magento setup:static-content:deploy'
alias bm2ir='./bin/magento indexer:reindex'
alias bm2irs='./bin/magento indexer:reset'
alias bm2mos='./bin/magento module:status'
alias bm2moe='./bin/magento module:enable'
alias bm2mod='./bin/magento module:disable'
alias bm2dev='./bin/magento deploy:mode:set developer'
alias bm2prod='./bin/magento deploy:mode:set production'
